### ISSUE TITLE
Does this only work with terminals *in* vscode?

### ISSUE THREAD

**Issue by ym-han** [haberdashPI/terminal-polyglot#6]
Does this only work with terminals *in* vscode? I'm asking because this seems similar to randy3k's SendCode plugin for Sublime Text, but that works also with terminals that aren't in sublime text.

**Comment by haberdashPI** [comment]
That's correct, this works only with terminals in VSCode. I'm not too familiar with the workflow or API for sending commands to a terminal outside VSCode, and don't use it myself. If someone is willing to take on testing and developing that bit, I'd be happy to accept it as a PR.

**Comment by haberdashPI** [comment]
Added some clarification to the README that this extension is for the integrated terminal in VSCode.
